---
- name: Install apache httpd  (state=present is optional)
  ansible.builtin.apt:
    name: apache2
    state: present

- name: apache service enable
  ansible.builtin.systemd:
    name: apache2
    enabled: true
    state: started
    daemon_reload: true

- name: remove default index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: git clone doom
  ansible.builtin.git:
    repo: 'https://github.com/healeycodes/doom-checkboxes.git'
    dest: '/var/www/html/index.html'
    force: yes