---

- name: Download URL 
  ansible.builtin.get_url:
    url: '{{ mario_url }}'
    dest: /root/mario.zip
    mode: '4777'

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - unzip
    - apache2
    - nodejs


- name: shell
  ansible.builtin.shell: cd /var/www/html/mario_js-master/ && npm install && npm start


- name: Unzip zip file
  ansible.builtin.unarchive:
    src: /root/mario.zip
    dest: /var/www/html/
    remote_src: yes