---
- name: Templates Playbook
  hosts: localhost
  vars:
    demo_variable: true
  tasks:
  - when: demo_variable
    block:
    - name: Write the config
      ansible.builtin.template:
        src: config.conf.j2
        dest: /tmp/config.conf
    - name: Print variable
      ansible.builtin.debug:
        msg: "demo_variable is {{ demo_variable }}"
        
  - name: Print variable again
    ansible.builtin.debug:
      msg: "demo_variable is again {{ demo_variable }}"