- name: Lookup Playbook
  hosts: localhost
  vars:
    demo_variable: "This is a demo variable"
  tasks:
    - name: Print the config
      ansible.builtin.debug:
        msg: "{{ lookup('file', '/tmp/config.conf') }}"